# configtx
# Used for setting up the Phase-3 of Airline Nw on the cloud

#   CAPABILITIES
Capabilities:
  Application: &ApplicationCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Channel: &ChannelCapabilities
    V2_0: true

# ORGANIZATIONS
Organizations:
  - &Orderer
    Name: OrdererMSP
    SkipAsForeign: false
    ID: OrdererMSP
    MSPDir: ../client/orderer/msp
    Policies: &OrdererPolicies
      Readers:
          Type: Signature
          Rule: "OR('OrdererMSP.member')"
      Writers:
          Type: Signature
          Rule: "OR('OrdererMSP.member')"
      Admins:
          Type: Signature
          Rule: "OR('OrdererMSP.member')"
      Endorsement:
          Type: Signature
          Rule: "OR('OrdererMSP.member')"

  - &Acme
    Name: AcmeMSP
    ID: AcmeMSP
    MSPDir: ../client/acme/msp
    Policies: &AcmePolicies
      Readers:
          Type: Signature
        #   Rule: "OR('AcmeMSP.admin', 'AcmeMSP.peer', 'AcmeMSP.client')"
          Rule: "OR('AcmeMSP.member')"
      Writers:
          Type: Signature
        #   Rule: "OR('AcmeMSP.admin', 'AcmeMSP.client')"
          Rule: "OR('AcmeMSP.member')"
      Admins:
          Type: Signature
          # UPDATE: Dec 15, 2019 - This is a dev env so its OK in Prod ... use AcmeMSP.admin
          Rule: "OR('AcmeMSP.member')"
      Endorsement:
          Type: Signature
          Rule: "OR('AcmeMSP.member')"
    AnchorPeers:
      - Host: acme-peer1.acme.com
        Port: 7051

  # Added by the Administrator
  - &Budget
    Name: BudgetMSP
    ID: BudgetMSP
    MSPDir: ../client/budget/msp
    Policies: &BudgetPolicies
      Readers:
          Type: Signature
        #   Rule: "OR('BudgetMSP.admin','BudgetMSP.peer','BudgetMSP.client')"
          Rule: "OR('BudgetMSP.member')"
      Writers:
          Type: Signature
        #   Rule: "OR('BudgetMSP.admin','BudgetMSP.client')"
          Rule: "OR('BudgetMSP.member')"
      Admins:
          Type: Signature
          # UPDATE: Dec 15, 2019 - This is a dev env so its OK in Prod ... use BudgetMSP.admin
          Rule: "OR('BudgetMSP.member')"
      Endorsement:
          Type: Signature
          Rule: "OR('BudgetMSP.member')"
    AnchorPeers:
      - Host: budget-peer1.budget.com
        Port: 8051

  

#   ORDERER
Orderer: &OrdererDefaults

  OrdererType: solo

  Addresses:
    - orderer.acme.com:7050

    # Policies for Orderer
  Policies:
    Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
    Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
    Admins:
        Type: ImplicitMeta  
        # UPDATED December 15, 2019
        Rule: "ANY Admins"
        # Rule: "MAJORITY Admins"

    # BlockValidation specifies what signatures must be included in the block
    # from the orderer for the peer to validate it.
    BlockValidation:
        Type: ImplicitMeta
        Rule: "ANY Writers"

  # Batch Timeout: The amount of time to wait before creating a batch
  BatchTimeout: 2s

  # Batch Size: Controls the number of messages batched into a block
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 98 MB
    PreferredMaxBytes: 512 KB



  Capabilities:
    <<: *OrdererCapabilities

Application: &ApplicationDefaults

  ACLs: &ACLsDefault
    # ACL policy for _lifecycle's "CheckCommitReadiness" function
    _lifecycle/CheckCommitReadiness: /Channel/Application/Writers

    # ACL policy for _lifecycle's "CommitChaincodeDefinition" function
    _lifecycle/CommitChaincodeDefinition: /Channel/Application/Writers

    # ACL policy for _lifecycle's "QueryChaincodeDefinition" function
    _lifecycle/QueryChaincodeDefinition: /Channel/Application/Readers

    # ACL policy for _lifecycle's "QueryChaincodeDefinitions" function
    _lifecycle/QueryChaincodeDefinitions: /Channel/Application/Readers
    
    # ACL policy for lscc's "getid" function
    lscc/ChaincodeExists: /Channel/Application/Readers

    # ACL policy for lscc's "getdepspec" function
    lscc/GetDeploymentSpec: /Channel/Application/Readers

    # ACL policy for lscc's "getccdata" function
    lscc/GetChaincodeData: /Channel/Application/Readers

    # ACL Policy for lscc's "getchaincodes" function
    lscc/GetInstantiatedChaincodes: /Channel/Application/Readers

    #---Query System Chaincode (qscc) function to policy mapping for access control---#

    # ACL policy for qscc's "GetChainInfo" function
    qscc/GetChainInfo: /Channel/Application/Readers

    # ACL policy for qscc's "GetBlockByNumber" function
    qscc/GetBlockByNumber: /Channel/Application/Readers

    # ACL policy for qscc's  "GetBlockByHash" function
    qscc/GetBlockByHash: /Channel/Application/Readers

    # ACL policy for qscc's "GetTransactionByID" function
    qscc/GetTransactionByID: /Channel/Application/Readers

    # ACL policy for qscc's "GetBlockByTxID" function
    qscc/GetBlockByTxID: /Channel/Application/Readers

    #---Configuration System Chaincode (cscc) function to policy mapping for access control---#

    # ACL policy for cscc's "GetConfigBlock" function
    cscc/GetConfigBlock: /Channel/Application/Readers

    # ACL policy for cscc's "GetConfigTree" function
    cscc/GetConfigTree: /Channel/Application/Readers

    # ACL policy for cscc's "SimulateConfigTreeUpdate" function
    cscc/SimulateConfigTreeUpdate: /Channel/Application/Readers

    #---Miscellanesous peer function to policy mapping for access control---#

    # ACL policy for invoking chaincodes on peer
    peer/Propose: /Channel/Application/Writers

    # ACL policy for chaincode to chaincode invocation
    peer/ChaincodeToChaincode: /Channel/Application/Readers

    #---Events resource to policy mapping for access control###---#

    # ACL policy for sending block events
    event/Block: /Channel/Application/Readers

    # ACL policy for sending filtered block events
    event/FilteredBlock: /Channel/Application/Readers


  # Default policies
  Policies: &ApplicationDefaultPolicies

    # approveformyorg
    LifecycleEndorsement:
        Type: ImplicitMeta
        # Rule: "MAJORITY Endorsement"
        Rule: "ANY Endorsement"
    
    # --channel-config-policy
    Endorsement:
        Type: ImplicitMeta
        # Rule: "MAJORITY Endorsement"
        Rule: "ANY Endorsement"

    Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
    Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
    Admins:
        Type: ImplicitMeta
        # UPDATED December 15, 2019
        # Rule: "MAJORITY Admins"
        Rule: "ANY Admins"

    StrictAdminPolicy:
        Type: ImplicitMeta
        Rule: "ANY Admins"
 
  Organizations:

  Capabilities:
    <<: *ApplicationCapabilities
 

#   CHANNEL
Channel: &ChannelDefaults
  Policies:
    Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
    Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
    Admins:
        Type: ImplicitMeta
        # UPDATED December 15, 2019
        # Rule: "MAJORITY Admins"
        Rule: "ANY Admins"

  Capabilities:
    <<: *ChannelCapabilities
  
#   PROFILES
Profiles:

  AirlineOrdererGenesis:
      <<: *ChannelDefaults
      Orderer:
          <<: *OrdererDefaults
          Organizations:
              - <<: *Orderer


      Application:
            <<: *ApplicationDefaults

            Organizations:
                - <<: *Acme               
                - <<: *Budget


      Consortiums:

        AirlineConsortium:
            
            Organizations:
                  - <<: *Acme                               
                  - <<: *Budget

                  
  AirlineChannel:
    <<: *ChannelDefaults
    Consortium: AirlineConsortium
        
    Application:
        <<: *ApplicationDefaults
        
        Organizations:
            - <<: *Acme
            - <<: *Budget



